Unifying and splitting iwyu workflows

diff --git a/.github/workflows/iwyu.yml b/.github/workflows/iwyu.yml
--- a/.github/workflows/iwyu.yml
+++ b/.github/workflows/iwyu.yml
@@ -43,6 +43,8 @@ jobs:
 
   iwyu:
     needs: check-changes
+    outputs:
+      has_errors: ${{ steps.run_iwyu.outputs.has_errors }}
     if: ${{ needs.check-changes.outputs.should_run == 'true' }}
     runs-on: ubuntu-24.04
     env:
@@ -118,25 +120,60 @@ jobs:
         make includes -j4 --silent TILES=${TILES:-0} SOUND=${SOUND:-0} LOCALIZE=${LOCALIZE:-0}
     - uses: ammaraskar/gcc-problem-matcher@0f9c86f9e693db67dacf53986e1674de5f2e5f28 # master
     - name: run IWYU
+      id: run_iwyu
       working-directory: Cataclysm-DDA
       env:
         IWYU_SRC_DIR: ${{ steps.build-iwyu.outputs.IWYU_SRC_DIR }}
         IWYU_BIN_DIR: ${{ steps.build-iwyu.outputs.IWYU_BIN_DIR }}
       run: |
+        echo +e
         PATH="${PATH}:${IWYU_BIN_DIR}:${IWYU_SRC_DIR}"
         python build-scripts/ci-iwyu-run.py
+        exit_code=$?
+        echo "has_errors=$exit_code" >> $GITHUB_OUTPUT
+        exit $exit_code
+    - name: Create pr comment artifacts
+      if: ${{ failed() && github.event_name == 'pull_request' && steps.run_iwyu.outputs.has_errors != 0 }}
+        set +e
+        cat files_changed | while read f; do
+          git add $f
+        done
+        git checkout .
+        git reset
+        git diff --exit-code
+        if [ $? -ne 0 ]; then
+          mkdir -p ./outputs
+          echo `git diff` > ./outputs/diff.txt
+          echo ${{ github.event.pull_request.number }} > ./outputs/pr_number
+          echo ${{ github.event.pull_request.head.sha }} > ./outputs/commit_sha
+        fi
+        exit 1
+    - name: Upload pr comment artifacts
+      if: ${{ failed() && github.event_name == 'pull_request' && steps.run_iwyu.outputs.has_errors != 0 }}
+      working-directory: Cataclysm-DDA
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+      with:
+        name: outputs
+        path: outputs/
+
 
   iwyu-result:
-    if: ${{ always() }}
+    if: ${{ !cancelled() }}
     needs: [iwyu]
     runs-on: ubuntu-latest
     steps:
     - name: require successful IWYU
+      env:
+        JOB_RESULT: ${{ needs.iwyu.result }}
+        JOB_ERRORS: ${{ needs.iwyu.outputs.has_errors }}
       run: |
-        result="${{ needs.iwyu.result }}"
-        if [ "$result" = "success" ] || [ "$result" = "skipped" ]; then
-          echo "IWYU result: $result"
+        if [[ "$JOB_RESULT" == "skipped" ]]; then
+          echo "IWYU result: skipped"
           exit 0
         fi
-        echo "IWYU failed with result: $result"
+        if [[ "$JOB_RESULT" == "success" && "$JOB_ERRORS" == "0" ]]; then
+          echo "IWYU result: success
+          exit 0
+        fi
+        echo "IWYU failed with result: $JOB_RESULT"
         exit 1
